### ISSUE TITLE
Eslint-loader - Webpack Plugin - Should we keep it?

### ISSUE THREAD

**Issue by andykenward** [Stinkstudios/create-react-app#216]
@Stinkstudios/developers-london-perm 

Should we keep [`eslint-loader`](https://github.com/webpack-contrib/eslint-loader) Webpack loader in create-react-app `@stinkstudios/react-scripts`?

Do people like having EsLint throw linting errors in the browser that you have to fix before your code will execute? 

Would you prefer an option to disable it as a `.env` setting perhaps? 

Or let CircleCi throw failed builds instead?

I've started to use [`pre-commit`](https://pre-commit.com/) to lint staged files before I can commit. Perhaps that would be a better option? And can be optional?

**Comment by patrick91** [comment]
+1 on removing and having optional pre-commit hook, should be opt-out tho, otherwise most of us won't enable it (I know I won't :D)

**Comment by andrewsellers** [comment]
I'd prefer the option to disabled it. As sometimes when you want to quickly try something you need to go on a commenting out mission to get the app to run :)

Really like the idea of pre-commit to lint staged files

**Comment by andykenward** [comment]
To give a bit more context on [`pre-commit`](https://pre-commit.com/) usage.

I used it on ray-ban.com-2018 to do the following
- check for merge conflict
- use prettier to format files
- eslint
- stylelint

Check the config out [`.pre-commit-config.yaml`](https://github.com/Stinkstudios/ray-ban.com-2018/blob/develop/.pre-commit-config.yaml)

**Comment by andykenward** [comment]
@patrick91 I am not sure pre-commit can be opt-out as you have to install it with pip or brew then run `pre-commit install` for every project usage.

**Comment by andykenward** [comment]
To give a bit more context on [pre-commit](https://pre-commit.com/) usage.

I used it on a previous project to do the following

 - check for merge conflict
- use prettier to format files
- eslint
- stylelint

[`.pre-commit-config.yaml`](https://github.com/Stinkstudios/ray-ban.com-2018)

**Comment by tyreer** [comment]
I'm just getting accustomed to it, but wouldn't mind switching it up for something else. Ditto to Andrew's point on commenting out.
