### ISSUE TITLE
post css custom properties preserve true

### ISSUE THREAD

**Issue by patrick91** [Stinkstudios/create-react-app#256]
Right now css variables are removed from compilation

**Comment by patrick91** [comment]
We also get this linting error, with preserve true:

```
(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/andrewsellers/Projects/stink-jukebox/frontend/src/base/vars/colors.css:9:3: Custom property ignored: not scoped to the top-level :root element (.cat-cat { ... --c-black: ... })
```

**Comment by patrick91** [comment]
To fix both "issues" add in the post css configuration:

	"customProperties": {
	    "preserve": true,
	    "warnings": false
	},

**Comment by andykenward** [comment]
@patrick91  https://www.npmjs.com/package/@stinkstudios/react-scripts/v/2.0.4 fixes this
